name: weather_app
description: A new Flutter project

publish_to: 'none' # Remove this line if you intend to publish to pub.dev

environment:
  sdk: "^3.9.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  shared_preferences: ^2.0.11
  intl: ^0.20.2
  characters: ^1.4.0  # Ensure this is version 1.4.0
  material_color_utilities: ^0.11.1
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  matcher: ^0.12.17
  test_api: ^0.7.6

flutter:
  uses-material-design: true
